name: Deploy MultiDocker
on:
  push:
    branches:
      - master
      
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: 'us-east-1'
  APPLICATION_NAME: 'MultiDocker'
  ENVIRONMENT_NAME: 'MultiDocker-env'
  BUCKET_NAME: 'elasticbeanstalk-us-east-1-847555796967'
  IMAGE_TAG: 'xkrb/MultiDocker'
  DOCKERFILE_DEV_PATH: 'Dockerfile.dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u "${{ env.DOCKER_USERNAME }}" -p "${{ env.DOCKER_PASSWORD }}"
      - run: docker build -t "${{ env.IMAGE_TAG }}" -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true "${{ env.IMAGE_TAG }}" npm test
 
      - run: docker build -t xkrb/multi-client-10-14 ./client
      - run: docker build -t xkrb/multi-nginx-10-14 ./nginx
      - run: docker build -t xkrb/multi-server-10-14 ./server
      - run: docker build -t xkrb/multi-worker-10-14 ./worker
 
      - run: docker push xkrb/multi-client-10-14
      - run: docker push xkrb/multi-nginx-10-14
      - run: docker push xkrb/multi-server-10-14
      - run: docker push xkrb/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "${{ env.APPLICATION_NAME }}"
          environment_name: "${{ env.ENVIRONMENT_NAME }}"
          existing_bucket_name: "${{ env.BUCKET_NAME }}"
          region: "${{ env.AWS_REGION }}"
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip